version: '3.4'

services:
  redis:
    image: redis:alpine
  
  postgres:
    image: postgres:latest
    environment:
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=HangfireJobs

  mongodb:
    image: mongo:latest


  aggregator:
    image: ${DOCKER_REGISTRY-}aggregator
    build:
      context: .
      dockerfile: BasketService/Dockerfile
    depends_on:
    - redis

  nashuabranch:
    image: ${DOCKER_REGISTRY-}nashuabranch
    build:
      context: .
      dockerfile: NashuaBranch/Dockerfile
    depends_on:
    - postgres
    - productservice

  orderservice:
    image: ${DOCKER_REGISTRY-}orderservice
    build:
      context: .
      dockerfile: OrderService/Dockerfile
    depends_on:
    - postgres


  productservice:
    image: ${DOCKER_REGISTRY-}productservice
    build:
      context: .
      dockerfile: ProductService/Dockerfile
    depends_on:
    - mongodb


  scrantonbranch:
    image: ${DOCKER_REGISTRY-}scrantonbranch
    build:
      context: .
      dockerfile: ScrantonBranch/Dockerfile
    depends_on:
    - postgres
    - productservice


  userservicejwt:
    image: ${DOCKER_REGISTRY-}userservicejwt
    build:
      context: .
      dockerfile: UserServiceJWT/Dockerfile
    depends_on:
    - postgres

